### ISSUE TITLE
First, thanks for your share of prcpsp. Now, may I ask you for two files that are algorithm outputs?

### ISSUE THREAD

**Issue by qiqishuang** [torressa/prcpsp#1]
prcpsp_code_file_line_134_and_135 outputs.

file_1: ./output/j30_results.txt
file_2: ./output/solution%s_%s.sol

It's my pleasure to receive your reply. I expect it so much.

**Comment by torressa** [comment]
Hi @qiqishuang!
Thanks for the comment, and sorry it took me so long, it went under my radar.
You just need to create a directory called `output` and create an empty file with name `j30_results.txt`.
That should work, I can upload mine so you can see what they look like.
Best,
David
